live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x71798a"
blue = "0x7aa6da"
cyan = "0x54ced6"
green = "0x9ec400"
magenta = "0xb77ee0"
red = "0xff3334"
white = "0xffffff"
yellow = "0xe7c547"

[colors.cursor]
cursor = "0xffd17f"
text = "0x2a2e38"

[colors.dim]
black = "0x333333"
blue = "0x6699cc"
cyan = "0x66cccc"
green = "0x99cc99"
magenta = "0xcc99cc"
red = "0xf2777a"
white = "0xdddddd"
yellow = "0xffcc66"

[colors.normal]
black = "0x2a2e38"
blue = "0xa6b8cc"
cyan = "0xffd17f"
green = "0x6f98b3"
magenta = "0xfcdbd9"
red = "0xd08785"
white = "0xf0fdff"
yellow = "0xfdf8ce"

[colors.primary]
background = "0x2a2e38"
foreground = "0xF0FDFF"

[colors.selection]
cursor = "0xF0FDFF"
text = "0x2a2e38"

[cursor]
unfocused_hollow = true

[cursor.style]
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.bold]
family = "MesloLGS NF"
style = "Bold"

[font.italic]
family = "MesloLGS NF"
style = "Italic"

[font.normal]
family = "MesloLGS NF"

[keyboard]
bindings = [
    # New tab (tmux)
    { key = "T", mods = "Command", chars = "\u0000c" },
    # Next tab (tmux)
    { key = "Right", mods = "Command|Option", chars = "\u0000n" },
    # Previous tab (tmux)
    { key = "Left", mods = "Command|Option", chars = "\u0000p" },
    # Clear buffer (tmux)
    { key = "k", mods = "Command", chars = "\u0000u" },
    # next word
    { key = "Right", mods = "Option", chars = "\u001BF" },
    # previous word
    { key = "Left", mods = "Option", chars = "\u001BB" },
]

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 100000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[shell]
program = "/Users/pichurri/homebrew/bin/zsh"

[window]
decorations = "full"
dynamic_padding = false
startup_mode = "Maximized"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 2
y = 2
