live_config_reload = true

import = ["~/.config/alacritty/themes/themes/catppuccin_mocha.toml"]

[cursor]
unfocused_hollow = true

[cursor.style]
shape = "Block"

[env]
TERM = "xterm-256color"

[terminal]
osc52 = "CopyPaste"

[font]
size = 16.0

[font.bold]
family = "MesloLGS NF"
style = "Bold"

[font.italic]
family = "MesloLGS NF"
style = "Italic"

[font.normal]
family = "MesloLGS NF"

[keyboard]
bindings = [
    # New tab (tmux)
    { key = "T", mods = "Command", chars = "\u0000c" },
    # Close pane (tmux)
    { key = "W", mods = "Command", chars = "\u0000x" },
    # Next tab (tmux)
    { key = "Right", mods = "Command|Option", chars = "\u0000n" },
    # Previous tab (tmux)
    { key = "Left", mods = "Command|Option", chars = "\u0000p" },
    # Clear buffer (tmux)
    { key = "k", mods = "Command", chars = "\u0000u" },
    # next word
    { key = "Right", mods = "Option", chars = "\u001Bf" },
    # previous word
    { key = "Left", mods = "Option", chars = "\u001Bb" },
    # beginning of line
    { key = "Left", mods = "Command", chars = "\u0001" },
    # end of line
    { key = "Right", mods = "Command", chars = "\u0005" },
    # delete left of cursor (with Back key)
    { key = "Back", mods = "Command", chars = "\u0015" },
    # forward delete character
    { key = "Delete", chars = "\u0004" },
]

[[hints.enabled]]
command = "open"
hyperlinks = true
mouse.enabled = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 100000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[shell]
program = "/Users/pichurri/homebrew/bin/zsh"

[window]
decorations = "full"
dynamic_padding = false
startup_mode = "Maximized"
option_as_alt = "Both"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 2
y = 2

[bell]
command = { program = "osascript", args = ["-e", "beep"] }
