[general]
live_config_reload = true

import = ["~/.config/alacritty/themes/themes/github_dark_default.toml"]

[cursor]
unfocused_hollow = true

[cursor.style]
shape = "Block"

[terminal]
osc52 = "CopyPaste"

[font]
size = 12.5

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"

[keyboard]
bindings = [
    # New tab (tmux)
    { key = "T", mods = "Command", chars = "\u0002c" },
    # Close pane (tmux)
    { key = "W", mods = "Command", chars = "\u0002x" },
    # Next tab (tmux)
    { key = "Right", mods = "Command|Option", chars = "\u0002n" },
    # Previous tab (tmux)
    { key = "Left", mods = "Command|Option", chars = "\u0002p" },
    # Clear buffer (tmux)
    { key = "k", mods = "Command", chars = "\u0002u" },

    # Copy buffer (tmux): Command+c -> tmux prefix+v
    { key = "c", mods = "Command|Option", chars = "\u0002v" },
    # Find in buffer
    { key = "f", mods = "Command", chars = "\u0002f" },
    # next word
    { key = "Right", mods = "Option", chars = "\u001Bf" },
    # previous word
    { key = "Left", mods = "Option", chars = "\u001Bb" },
    # beginning of line
    { key = "Left", mods = "Command", chars = "\u0001" },
    # end of line
    { key = "Right", mods = "Command", chars = "\u0005" },
    # delete left of cursor (with Back key)
    { key = "Back", mods = "Command", chars = "\u0015" },
    # forward delete character
    { key = "Delete", chars = "\u0004" },
    # Properly send Shift + Enter
    { key = "Return", mods = "Shift", chars = "\u001b[13;2u" },
    # Command + A, for nvim 'Select all'
    { key = "a", mods = "Command", chars = "\u001ba" },
]

[[hints.enabled]]
command = "open"
hyperlinks = true
mouse.enabled = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 100000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "Buttonless"
dynamic_padding = false
startup_mode = "SimpleFullscreen"
option_as_alt = "Both"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 2
y = 2

[bell]
duration = 40
command = { program = "osascript", args = ["-e", "beep"] }
