# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# palette = "catppuccin_mocha"

add_newline = false

format = """$os\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$fill\
$username@$hostname\
$cmd_duration\
$all\
$time\
$line_break\
$character"""

[fill]
style = 'fg:#707070'


[directory]
truncate_to_repo = false
truncation_length = 8

[cmd_duration]
format = " $duration "

[time]
disabled = false
format = " [$time]() "
time_format = '%T'

[conda]
format = '[$symbol$environment]($style) '

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[os]
disabled = false

[os.symbols]
Alpine = " "
Macos = " "
NixOS = "❄️ "

[hostname]
ssh_only = false
disabled = false
format = "[$hostname]($style) "
style = "bold purple"

[username]
disabled = false
show_always = true
format = "[$user]($style)"

[git_branch]
symbol = "  "
format = '[$symbol$branch(:$remote_branch)]($style) '

[git_status]
behind = "⇣$count "
conflicted = "$count "
untracked = "?$count "
staged = "+$count "
modified = "!$count "
ahead = "⇡$count "

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
